### ISSUE TITLE
Import only used lodash methods

### ISSUE THREAD

**Issue by th3fallen** [alsoscotland/react-super-select#101]
instead of `import _ from 'lodash'` as seen in https://github.com/alsoscotland/react-super-select/blob/master/src/react-super-select.js#L11

do `import {values, uniqueId, bindAll, isArray, isFunction, isUndefined, isEqual, extend, isEmpty, head, isObject, isString, map, reject, includes, isNumber, groupBy, forIn, find, noop, reduce, } from 'lodash';` < jeez you use a ton of them....

**Comment by alsoscotland** [comment]
Thanks!  
https://github.com/alsoscotland/react-super-select/tree/v0.5.16

**Comment by th3fallen** [comment]
also on that topic is there a reason you use lodash's `_.map` method vs the built in one?

**Comment by alsoscotland** [comment]
@th3fallen I started this component with some pre-babel ES5 code.  Never converted it.  Interestingly though, check this out https://jsperf.com/native-map-vs-lodash-map

**Comment by th3fallen** [comment]
well, i'll be damned.... point taken... TIL
