### ISSUE TITLE
opt-group parents selectable?

### ISSUE THREAD

**Issue by th3fallen** [alsoscotland/react-super-select#103]
is there any way to make a parent selectable?

**Comment by alsoscotland** [comment]
@th3fallen is the intention that selecting a group heading would effectively multi-select all child-options in the group?
That would be a challenge to do while maintaining the keyboard accessibility of the control

**Comment by th3fallen** [comment]
@alsoscotland no, the goal would be for the group heading to be assigned a value and be selectable just like a child.

**Comment by alsoscotland** [comment]
@th3fallen 
sorry for the delayed response. The way group headings work now is that they are non-focusable and they use the aria role 'separator'.  At present I don't think it makes sense to refactor it to work this way in the control for the general use-case of a select
