### ISSUE TITLE
Is there any possibility of leaving the super-select field required?

### ISSUE THREAD

**Issue by eduardobarbiero** [alsoscotland/react-super-select#104]
In some specific cases we can add a markup tag and a break in the form submit to prevent submitting when there are incorrect occurrences in the form.

```html
<em id="name-error" class="invalid">Required field.</em>
```
If there is any interest on the part of the master of the component, I can assist in the development.

**Comment by alsoscotland** [comment]
@eduardobarbiero 
Always happy to have help but I am not following exactly.  Can you please explain the scenario a bit further?

**Comment by eduardobarbiero** [comment]
Hello @alsoscotland!

Basically leave the field created by super-select as required within a form, preventing the submit if the value not is expected (a blank value for example).

Did i express myself well?

**Comment by alsoscotland** [comment]
@eduardobarbiero closing since per our conversation you found a workaround
