### ISSUE TITLE
noResultsString does not appear when groupBy is present

### ISSUE THREAD

**Issue by 92arpitgoyal** [alsoscotland/react-super-select#107]
When `groupBy` is set, `noResultsString`('No Result Found' by default) stop to work, even if there is no match for string being searched.

**Comment by 92arpitgoyal** [comment]
https://github.com/alsoscotland/react-super-select/pull/108

**Comment by alsoscotland** [comment]
@92arpitgoyal Thank you for filing the bug and for the fix

**Comment by alsoscotland** [comment]
Addressed in https://github.com/alsoscotland/react-super-select/tree/v1.0.1
