### ISSUE TITLE
Set options selected manually

### ISSUE THREAD

**Issue by robinprashanth** [alsoscotland/react-super-select#110]
I am using react super select in my project.I am facing issue where i need to reset the option selected to first object in the array.

Steps to reproduce
1)select some value from the dropdown
2)I have a button event-> when clicked-> reset the selected option to the fist option or desired option in the dropdown.

Hope you can help me

**Comment by alsoscotland** [comment]
@robinprashanth 
any outside event that updates the super-select's initialValue prop should result in that value being selected

**Comment by robinprashanth** [comment]
I found the solution.Thanks for the help.

**Comment by alsoscotland** [comment]
Glad to hear it
