### ISSUE TITLE
Numeric values and keys

### ISSUE THREAD

**Issue by gitolog** [alsoscotland/react-super-select#111]
dataSource={[
  {"anchor":156,"label":156},
  {"anchor":168,"label":168},
  {"anchor":185,"label":185},
  {"anchor":205,"label":205}
]}
optionValueKey='anchor'
optionLabelKey='label'

React super select returns 'no data'

**Comment by alsoscotland** [comment]
@gitolog
Thanks for filing the issue.  I will take a look

**Comment by alsoscotland** [comment]
@gitolog 
Should be addressed.  https://github.com/alsoscotland/react-super-select/tree/v1.0.2

**Comment by gitolog** [comment]
@alsoscotland
Thank you! It seems all working well

**Comment by alsoscotland** [comment]
@gitolog Thanks for letting me know!  Glad it is working for you
