### ISSUE TITLE
Call onChange when clearSelectedValueOnDataSourceChange changes value

### ISSUE THREAD

**Issue by VikLiegostaiev** [alsoscotland/react-super-select#113]
Hi, when dataSource changes and clearSelectedValueOnDataSourceChange is true then value changes to empty array, but it doesn't call onChange function with this newValue. Can you please add this?

**Comment by alsoscotland** [comment]
@VikLiegostaiev 
I will take a look

**Comment by alsoscotland** [comment]
@VikLiegostaiev  
I think this is all that it needs.  Would you be able to verify if that branch does what you need?
https://github.com/alsoscotland/react-super-select/pull/114

**Comment by VikLiegostaiev** [comment]
Yes it is, thanks. Will you add this to master branch?

**Comment by alsoscotland** [comment]
@VikLiegostaiev 
released https://github.com/alsoscotland/react-super-select/tree/v1.0.3
