### ISSUE TITLE
create onClear callback

### ISSUE THREAD

**Issue by VikLiegostaiev** [alsoscotland/react-super-select#115]
Hi again, can you please add onClear callback, mean when i clear selected values with clear cross.

**Comment by prdebski** [comment]
I need that too

**Comment by alsoscotland** [comment]
@VikLiegostaiev @prdebski 
please let me know if this does what you need
https://github.com/alsoscotland/react-super-select/pull/116

**Comment by prdebski** [comment]
Yes it does, thanks!

**Comment by alsoscotland** [comment]
@VikLiegostaiev @prdebski 
https://github.com/alsoscotland/react-super-select/tree/v1.0.4
