### ISSUE TITLE
Is there any possibility of leaving the super-select field noResultsString as template? 

### ISSUE THREAD

**Issue by eduardobarbiero** [alsoscotland/react-super-select#119]
In some specific cases we use a template for perform some action when there are no items in that select list.
Example:
```html
noResultsTemplate={ () => <TemplateForNoItens /> }
```
If there is any interest on the part of the master of the component, I can assist in the development.

**Comment by alsoscotland** [comment]
@eduardobarbiero That would be great.  I would be happy to accept a pull for that

**Comment by alsoscotland** [comment]
@eduardobarbiero Let me know if this would work for you.  I just overloaded the prop type for noResultsString to allow for React Elements as well.
https://github.com/alsoscotland/react-super-select/pull/124

**Comment by eduardobarbiero** [comment]
@alsoscotland exactly!

**Comment by alsoscotland** [comment]
@eduardobarbiero 
Done https://github.com/alsoscotland/react-super-select/tree/v1.0.7
