### ISSUE TITLE
Add possibility to pass component as placeholder

### ISSUE THREAD

**Issue by prdebski** [alsoscotland/react-super-select#120]
That would be nice to have possibility to pass component as placeholder.
Now when passing component I got warning: "Failed prop type: Invalid prop `placeholder` of type `object` supplied to `ReactSuperSelect`, expected `string`."

**Comment by alsoscotland** [comment]
@prdebski placeholder is used as the value for the html attribute placeholder.  It would not be semantic to allow components there
