### ISSUE TITLE
Multiselect with Shift-key problem

### ISSUE THREAD

**Issue by a1argus** [alsoscotland/react-super-select#122]
Multiselect with Shift-key not working if values are numerics converted to string
like this:
dataSource={[
{"name":100,"value":"100"},
{"name":200,"value":"200"},
{"name":300,"value":"300"},
]}

  **_getOptionValueFromDataAttr** converts them opportunistically to numerics
but then **_selectAllOptionsInOptionIdRange** compares them to string and gets nothing

**Comment by alsoscotland** [comment]
@a1argus I will take a look at this soon.

**Comment by alsoscotland** [comment]
@a1argus Thanks for filing the bug.  
https://github.com/alsoscotland/react-super-select/tree/v1.0.6
