### ISSUE TITLE
Fallback to native select on mobile

### ISSUE THREAD

**Issue by andreivictor** [alsoscotland/react-super-select#125]
Is it possible to deactivate the dropdown menu on mobile devices, to use the built-in select of the OS for a better UX?

**Comment by alsoscotland** [comment]
@andreivictor The control is pretty coupled with react-dom at this point.  I am sure sure how to go about this.  Do you have any suggestions?

**Comment by alsoscotland** [comment]
@andreivictor closing for now

**Comment by andreivictor** [comment]
@alsoscotland, thanks. I was thinking about adding a <select> element in the DOM, that will be hidden on large screens and visible on mobile devices. But I will try to fork and come up with a complete solution when I'll have some spare time on my hands.
