### ISSUE TITLE
initialValue as empty array or empty object

### ISSUE THREAD

**Issue by robinprashanth** [alsoscotland/react-super-select#129]
I am working on a project were the select option is optional in the create form. In Edit form, I need to set initialValue based on the API response. Is there any option to pass empty array or object to reactsuperselect.

Example
constructor(props) {
    super(props);
    this.state = {
      errors: {},
      recNumberInitialValue: undefined
    };
  }
componentDidMount(){
getAPIrequest.then((resp) => thissetState({recNumberInitialValue: resp}))
}

<ReactSuperSelect
                          className="form-input"
                          dataSource={this.recNumbers}
                          onChange={this.recHandler}
                          deselectOnSelectedOptionClick={false}
                          initialValue={this.state.recNumberInitialValue}
                          clearable={false}
                        />

here recNumberInitialValue is undefined or a value based on the API response. 

I am getting 
Failed prop type: Invalid prop `initialValue` supplied to `ReactSuperSelect`.

Can you suggest If i can pass empty object or array as intialValue?

**Comment by alsoscotland** [comment]
@robinprashanth 
The code should handle the case where
```
 initialValue={undefined}
```
I think empty array should be fine as well.  
Another option would be to simply not render super select at all if no options are available

**Comment by robinprashanth** [comment]
I have to show super select even if it's not having any initialValue. If i pass empty array it breaks with error : name property was not found

**Comment by alsoscotland** [comment]
Is there a reason you are not able to just leave initialValue undefined?

**Comment by robinprashanth** [comment]
Undefined did the trick.Thanks for the help.

**Comment by alsoscotland** [comment]
No problem @robinprashanth
