### ISSUE TITLE
unable to run example in react cli 

### ISSUE THREAD

**Issue by skkohli** [alsoscotland/react-super-select#131]
I might be doing something wrong here. I used npm install in the project created by react cli. When i include the library import {ReactSuperSelect} from 'react-super-select/lib/react-super-select'; i errors that **Element type is invalid:**
I also dont see any examples in the github repo to run it

**Comment by alsoscotland** [comment]
@skkohli 
I think it is likely just a problem with your import statement.
```
import ReactSuperSelect from 'react-super-select';
```
rather than 
import { ReactSuperSelect }

ReactSuperSelect is the only export of the package.
Please let me know if that solves your issue

**Comment by skkohli** [comment]
Yes, That was a mistake. Thanks for the amazing component @alsoscotland

**Comment by alsoscotland** [comment]
@skkohli no worries.  Glad it is working!
