### ISSUE TITLE
Remove Selected Option From List

### ISSUE THREAD

**Issue by tjbenneche** [alsoscotland/react-super-select#132]
Is there a way to remove a selected option from the options list? Right now I'm hiding them with CSS, but I would like to be able to key down through the list without needing extra presses to get past the hidden list items.

**Comment by alsoscotland** [comment]
@tjbenneche This doesn't work out of the box as it doesn't really follow the paradigm of an html select control.  That said though, it should be manageable if you just make a wrapping component that keeps track of the selected options in its state.  You would just have to filter the options supplied to the super-select in the wrapping component.
