### ISSUE TITLE
Encountered two children with the same key, `drop_li_undefined`

### ISSUE THREAD

**Issue by conor909** [alsoscotland/react-super-select#133]
How do I add keys to dropdown children?

**Comment by alsoscotland** [comment]
@conor909 The keys are generated programatically based on your options 'id' or whatever key name you supply to the optionValueKey prop.

If you are seeing duplicate key errors, I suspect the issue is that you have more than one option with the same value in your options data

**Comment by conor909** [comment]
Thanks!  Sorry I didn't realise an `id` was required.
