### ISSUE TITLE
onSearchInputChange isn't called after select an option with clearSearchOnSelection prop active.

### ISSUE THREAD

**Issue by VikLiegostaiev** [alsoscotland/react-super-select#137]
Hello.
I wrote something in search input, then I selected option, dropdown closed and search input cleared but no call of onSearchInputChange. Is this should work in such way or is this a bug? Maybe, is there another way to callback when search is cleared on selection?

**Comment by alsoscotland** [comment]
@VikLiegostaiev Might be a bug.  I will take a look soon

**Comment by alsoscotland** [comment]
@VikLiegostaiev 
my apologies that this took a while.  Let me know if the issue is solved in
https://github.com/alsoscotland/react-super-select/tree/v1.0.10
