### ISSUE TITLE
&..; symbols and html tags within a displayed label are being escaped

### ISSUE THREAD

**Issue by ccav01** [alsoscotland/react-super-select#139]
Nevermind, it's react doing it not your code.  My apologies, close this.

**Comment by alsoscotland** [comment]
@ccav01 no worries.  you might be able to solve the problem with https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml in a custom template

**Comment by ccav01** [comment]
Yep, I found that right after I sent the notice.  :)  Thanks for touching
base with me.  I'm going to try a custom option template that returns <span
dangerously... and see if it makes it through.
