### ISSUE TITLE
Custom selected tag template

### ISSUE THREAD

**Issue by TimNZ** [alsoscotland/react-super-select#142]
Hey mate

Great alternative to react-select which has patchy support and long awaited PR pending i.e. ajax paging, thanks!

Is there a reason you haven't supported selected tag templates?

I find yours a bit ugly, and overriding all your CSS is fiddly.

**Comment by TimNZ** [comment]
Not an issue, can extend the class and override the relevant methods

**Comment by alsoscotland** [comment]
@TimNZ 
Glad you like the control.  The intention was a very generic UI by default that can be overridden pretty easily.  Let me know if you need any guidance.
