### ISSUE TITLE
Doesn't close select on outside click

### ISSUE THREAD

**Issue by VikLiegostaiev** [alsoscotland/react-super-select#145]
Hi again!

There is one problem, can you check pls? 

When I pass the disabled prop equal to true from parent's component state to react-super-select, it works great - block component. However, when I change this property to false with setState, it updates react-super-select, but I can't close the component on outside click  Only when disabled prop is false on the mounting of component then I can close it on outside click. 

I think this shouldn't behave in such way or maybe I did something wrong.

Thanks for supporting, great component!

**Comment by alsoscotland** [comment]
Hello again @VikLiegostaiev 
This may fix it but if not please let me know.  There are another couple lines I may need to adjust
https://github.com/alsoscotland/react-super-select/tree/v1.0.14

**Comment by VikLiegostaiev** [comment]
It hasn't been fixed, the same behaviour.

**Comment by alsoscotland** [comment]
Thanks.  Wasn't sure.  will take another look

**Comment by alsoscotland** [comment]
@VikLiegostaiev Give this a shot
https://github.com/alsoscotland/react-super-select/tree/v1.0.17
