### ISSUE TITLE
customOptionTemplateFunction 

### ISSUE THREAD

**Issue by devalf** [alsoscotland/react-super-select#162]
When I use `customOptionTemplateFunction` I got `Warning: Each child in an array or iterator should have a unique "key" prop.` error in console. The same issue is present on the package demo page.

**Comment by alsoscotland** [comment]
Thanks for letting me know @devalf. I will take a look soon

**Comment by alsoscotland** [comment]
@devalf Thanks again.  Apologies it took me a while to get to it
https://github.com/alsoscotland/react-super-select/tree/v1.0.20
