### ISSUE TITLE
Getting Object doesn't support property or method 'contains' in IE11

### ISSUE THREAD

**Issue by a2441918** [alsoscotland/react-super-select#165]
Hi, I am trying to use this component but get 'Object doesn't support property or method 'contains'' in IE.  Chrome works fine. I installed core-js and regenerator-runtime as polyfills. Please advice.

[https://stackblitz.com/edit/react-qvhjub?file=index.js](https://stackblitz.com/edit/react-qvhjub?file=index.js)

**Comment by alsoscotland** [comment]
@a2441918 please try https://github.com/alsoscotland/react-super-select/tree/v1.0.22
It seems like IE11 does not support contains on the document
