### ISSUE TITLE
Problem with setting initialValues through componentWillReceiveProps 

### ISSUE THREAD

**Issue by joewood** [alsoscotland/react-super-select#29]
When the component is rendered multiple times and React invokes `componentWillReceiveProps` the changing value of **initialValue** is ignored. It looks like the initialization code around setting the values isn't called when the component is remounted.

**Comment by alsoscotland** [comment]
@joewood Thanks for filing the issue.  I will get this taken care of shortly

**Comment by alsoscotland** [comment]
@joewood 
I think that pull https://github.com/alsoscotland/react-super-select/pull/30 should cover it.

**Comment by joewood** [comment]
Thanks @alsoscotland. It's a great component!

**Comment by alsoscotland** [comment]
I appreciate it @joewood 
Glad you are finding it useful!
I will merge this and tag a new branch soon.  I am hoping to get a couple other minor modifications in alongside it.

**Comment by alsoscotland** [comment]
This should be fixed in version 0.1.16
