### ISSUE TITLE
customFilterFunction

### ISSUE THREAD

**Issue by hmeerlo** [alsoscotland/react-super-select#31]
Hi,

your component looks pretty nice. But I would like to use the customFilterFunction but how would my custom filter know what to filter on if the input handling is completely handled by ReactSuperSelect. I only get the option as an parameter, but not the search text.

/Herman

**Comment by alsoscotland** [comment]
@hmeerlo  Thanks for filing the issue.  My apologies for the late reply, I wasn't working over the holiday weekend.  Looks like an oversight on my part.  I will get a fix in and tag a new version

**Comment by alsoscotland** [comment]
@hmeerlo You should have access to the searchString if you install v0.1.18
https://github.com/alsoscotland/react-super-select/tree/v0.1.18
Thanks Again!

**Comment by hmeerlo** [comment]
Thanks, I will give it a try.
