### ISSUE TITLE
Unset chosen value

### ISSUE THREAD

**Issue by hmeerlo** [alsoscotland/react-super-select#36]
Hi,

is there any way to unset the chosen value? The user selects a value from the dropdown but later on he wants to unselect it. How to do this?

/Herman

**Comment by alsoscotland** [comment]
@hmeerlo currently the use has to re-click the selected option.  In one of the next pulls I make I think I will implement clear button functionality.  If you have requests as to what it should look like I am open to hearing them

**Comment by hmeerlo** [comment]
@alsoscotland I think a simple method would suffice. So the user can implement his own selection clearing. Maybe an optional property to include a clear button as you suggest.

**Comment by hmeerlo** [comment]
@alsoscotland By the way, re-clicking the selected option does not unselect it for me. I can not even click on the selected option. Also on the live examples it doesn't work that way.

**Comment by alsoscotland** [comment]
@hmeerlo my apologies.  It has been a bit since I wrote it.  You are absolutely right.  I will get a clear function in soon

**Comment by alsoscotland** [comment]
@hmeerlo Apologies that it took longer than expected.  0.1.19 should have this for you

**Comment by hmeerlo** [comment]
@alsoscotland No problem, thanks!
