### ISSUE TITLE
Need a way to reset search text on multiselect + search + tags

### ISSUE THREAD

**Issue by z3ugma** [alsoscotland/react-super-select#37]
When calling a component that has multiselect, searchable, and tags all = true, the search text does not reset itself onChange.

This makes it difficult for the user to make the next selection if they are searching through a long list. They first have to delete all the text they previously searched for.

**Comment by alsoscotland** [comment]
@z3ugma thanks for submitting.  I plan to work on the control a bit this week so I will look into it

**Comment by z3ugma** [comment]
Any word on implementing this?

**Comment by alsoscotland** [comment]
@z3ugma I have it almost done.  Just wrapping up specs and some css.

**Comment by z3ugma** [comment]
👍🏻👍🏻🤓

**Comment by alsoscotland** [comment]
@z3ugma 0.1.19 should do what you need.  Please let me know if you run into any issues.  Closing for now
