### ISSUE TITLE
Uncaught Error: Cannot find module 'react'

### ISSUE THREAD

**Issue by mkotar** [alsoscotland/react-super-select#44]
Hi,
after upgrading to newest version 0.2.0

I get one error:
react-super-select.js:1     Uncaught Error: Cannot find module 'react'

and one warning 
WARNING in ./~/react-super-select/lib/react-super-select.js
Critical dependencies:
1:132-139 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-super-select/lib/react-super-select.js 1:132-139

this is webpack build process and the first one is in chrome's console.

I have newest webpac, react, react dom, react rooter etc...

**Comment by alsoscotland** [comment]
@mkotar 
was v0.1.19 working with the same build setup?  In moving to v0.2.0 I changed how I configured the file for external peerDependencies.

**Comment by mkotar** [comment]
No. 0.19 was not passing the build process.

**Comment by alsoscotland** [comment]
Okay.  going to investigate further

**Comment by mkotar** [comment]
Hi, I've updated to 2.1 and now I have this:
Uncaught Error: Cannot find module 'lodash' in react-super-select.js:1 in chrome dev tools

and a warning in webpack process
WARNING in ./~/react-super-select/lib/react-super-select.js
Critical dependencies:
7:76-84 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-super-select/lib/react-super-select.js 7:76-84

**Comment by alsoscotland** [comment]
Michal,
There are still some issues I am trying to work out since upgrading to React 14+.I am going to take a look in the next couple days.Can you tell me the last version you had that was working properly for you?
Thanks,Scotland 


    On Thursday, November 26, 2015 4:11 AM, Michał <notifications@github.com> wrote:
 

 Hi, I've updated to 2.1 and now I have this:
Uncaught Error: Cannot find module 'lodash' in react-super-select.js:1 in chrome dev toolsand a warning in webpack process
WARNING in ./~/react-super-select/lib/react-super-select.js
Critical dependencies:
7:76-84 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-super-select/lib/react-super-select.js 7:76-84—

**Comment by hmeerlo** [comment]
I have got the exact same problem as @mkotar. 0.1.18 was still working for me but that lacks React 0.14 support so I tried to upgrade to 2.1. Why is 0.1.19 and above now published as a bundled/prebuilt package on npm? Somehow webpack doesn't like this.

**Comment by alsoscotland** [comment]
I released 0.2.2 tonight.  Please let me know if that solves your issues.
Thank you,Scotland 


    On Thursday, November 26, 2015 4:11 AM, Michał <notifications@github.com> wrote:
 

 Hi, I've updated to 2.1 and now I have this:
Uncaught Error: Cannot find module 'lodash' in react-super-select.js:1 in chrome dev toolsand a warning in webpack process
WARNING in ./~/react-super-select/lib/react-super-select.js
Critical dependencies:
7:76-84 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/react-super-select/lib/react-super-select.js 7:76-84—

**Comment by hmeerlo** [comment]
Thanx @alsoscotland , it works for me now!

**Comment by mkotar** [comment]
Now it works ;)

**Comment by alsoscotland** [comment]
@mkotar and @hmeerlo  thanks for the help and the reporting.  Closing for now.  Let me know if any other issues come up
