### ISSUE TITLE
Close on click outside select dropdown

### ISSUE THREAD

**Issue by oyeanuj** [alsoscotland/react-super-select#47]
Hi @alsoscotland! I am wondering if there is a way to configure the select dropdown to close when there is a click outside the dropdown?

**Comment by alsoscotland** [comment]
@oyeanuj I have considered it in the past but opted not to.  I did not think it fit everyone's use case to do so.  I will look into level of effort for adding that as a configurable option

**Comment by oyeanuj** [comment]
I see. Let me know if you make it a configurable option - fit's everyone use-case :)

As an aside, I am curious for what use-cases do folks prefer it not closing the select dropdown when clicking outside?

**Comment by alsoscotland** [comment]
@oyeanuj I did not have an exact use case in mind but was debating in general whether it could potentially have a negative impact on any UI scenarios.  It would most likely be fine for everyone

**Comment by alsoscotland** [comment]
@oyeanuj please see if https://github.com/alsoscotland/react-super-select/tree/v0.2.3 resolves this issue for you when you have the chance.  
Thanks again.  

Still T.B.D. on the the other issue you filed.

**Comment by oyeanuj** [comment]
Yes, this works! Thanks so much!

Looking forward to the other issue being resolved :)
