### ISSUE TITLE
_.findWhere is not a function

### ISSUE THREAD

**Issue by daversm** [alsoscotland/react-super-select#51]
I am getting this error, 

I just did npm install 
var ReactSuperSelect = require('react-super-select');

**Comment by alsoscotland** [comment]
@daversm 
Lodash as of version 4+ has removed findWhere. I built this component prior to that release.

I will work on updating any deprecated methods I am using this week.
For now, you can use the control if you lock your lodash version < 4

**Comment by daversm** [comment]
Using lodash <4 now .. Works perfectly now..much thanks for the quick response

**Comment by alsoscotland** [comment]
Now compatible with lodash 4 upgrades
https://github.com/alsoscotland/react-super-select/releases/tag/v0.3.1
