### ISSUE TITLE
height

### ISSUE THREAD

**Issue by daversm** [alsoscotland/react-super-select#52]
Is changing the height of the drop down menu hard? I was looking around CSS file a bit, but a little lost as to what to change.

**Comment by alsoscotland** [comment]
@daversm 
There is a max-height rule on the class "r-ss-dropdown"

you should be able to override the rules with by adding a more specific wrapping class with the 
customClass attribute: http://alsoscotland.github.io/react-super-select/#customClass 

example:
if you give the option customClass: "daversm"
```css
.daversm .r-ss-dropdown {
  max-height: none;
}
```
