### ISSUE TITLE
v 0.4.0 with React 0.13.x is throwing an error

### ISSUE THREAD

**Issue by anuccio1** [alsoscotland/react-super-select#60]
I was previously using v 0.1.16, and wasn't able to deselect in my multiselect dropdown, so I upgraded to 0.4.0, however now I am getting this error in my console:

Uncaught TypeError: this.refs.rssControl.contains is not a function_handleDocumentClick @ react-super-select.js?8d48:936

Is there a working version compatible with React 0.13.x???

**Comment by alsoscotland** [comment]
@anuccio1 The last version that worked for React <14 was 
0.1.19
Give that a try and let me know what happens.

**Comment by anuccio1** [comment]
Looks like that fixed that issue! Another question....looks like the clear all button isn't triggering on change...was this fixed in a future release as well?

**Comment by alsoscotland** [comment]
@anuccio1 yes.  Unfortunately, that fix came after the upgrade so it may be a challenge to cherry-pick it.  Try making a fork and adding the equivalent of this commit https://github.com/alsoscotland/react-super-select/commit/a51e6fe803e049b63f878f6eb45a2d37828fa5fd
