### ISSUE TITLE
Clear Search Input and reset filter after selecting an Item from searchable dropdown

### ISSUE THREAD

**Issue by amgohan** [alsoscotland/react-super-select#62]
Can you add an option to be able to clear the search input and reset the filter after selecting an Item.

Use case : 
- expand the drop down (searchable)
- tape something in input to filter the list
- select the wanted option (the drop down close automatically)
- when expand the dropdown for the second time the input value is there and the filter still there

we want to clear the input and reset the filter after the first select.

**Comment by alsoscotland** [comment]
@amgohan 
I think this likely makes sense as an option.  Can you tell me more about the configuration you are using?  Is it a multiselect or tag input?

**Comment by amgohan** [comment]
this is what we use now
```
<Select placeholder="Select something"
                              dataSource={data}
                              onChange={this.change}
                              searchable={true}
                              clearable={false} />
```

the behaviour we want : 
every time we expand the drop down we want to start from scratch for filtering (no filter applied and focus on the input)

**Comment by alsoscotland** [comment]
@amgohan Sure.  I can make that an option.  I will try to get it done in the next day or two

**Comment by amgohan** [comment]
Thanks, by the way you did an awesome work in this component

**Comment by alsoscotland** [comment]
@amgohan Thank you!  Very glad to have people finding it useful

**Comment by alsoscotland** [comment]
@amgohan 
Still working on this.  Just wanted to let you know

**Comment by amgohan** [comment]
@alsoscotland thanks for the update

**Comment by alsoscotland** [comment]
https://github.com/alsoscotland/react-super-select/pull/68

**Comment by alsoscotland** [comment]
https://github.com/alsoscotland/react-super-select/tree/v0.5.0
