### ISSUE TITLE
Drop down close when clicking on button clear in search input

### ISSUE THREAD

**Issue by amgohan** [alsoscotland/react-super-select#63]
when using searchable dropdown and entering some strings in search input.
if we want to clear this input we click on the button clear. but when clicking the dropdown close.
we want that when we clear the input via the button, the dropdown remain open.

**Comment by alsoscotland** [comment]
@amgohan 
Just making sure I understand what you are asking correctly:
You would like the drop down to remain open when clicking the clear button for the search input field?

**Comment by amgohan** [comment]
yes exactly

**Comment by alsoscotland** [comment]
Sure.  This seems like a bug actually

**Comment by alsoscotland** [comment]
https://github.com/alsoscotland/react-super-select/pull/68

**Comment by alsoscotland** [comment]
https://github.com/alsoscotland/react-super-select/tree/v0.5.0
