### ISSUE TITLE
Focus on Search Input when expand dropdown on searchable dropdown

### ISSUE THREAD

**Issue by amgohan** [alsoscotland/react-super-select#64]
We want to auto-focus on search input when dropdown is expanded

**Comment by alsoscotland** [comment]
@amgohan On first expansion of the searchable control the search input field is the first thing that receives focus?  Could you give me more info around when it is not focusing like you would expect.

**Comment by amgohan** [comment]
You are right, in the first expand the input field is the first thing that receives focus.

What we expect, every time we expand after selection, we want that the input be focused, not the selected value

**Comment by alsoscotland** [comment]
I need to verify that changing that does not break the expected accessibility behavior

**Comment by amgohan** [comment]
this can be part of the issue #62, if you add an option to clear search and start from scratch for filter with focus on input search every time we expand the dropdown

**Comment by alsoscotland** [comment]
https://github.com/alsoscotland/react-super-select/pull/68

**Comment by alsoscotland** [comment]
https://github.com/alsoscotland/react-super-select/tree/v0.5.0
