### ISSUE TITLE
when text is long in (r-ss-selected-label) it exceeds the margin of rss_1

### ISSUE THREAD

**Issue by amgohan** [alsoscotland/react-super-select#65]
this is well handled in ul (r-ss-dropdown-options) dropdown, when select a long text it exceeds the margin of rss_1.

![superselect](https://cloud.githubusercontent.com/assets/3297683/15905229/1e323d30-2d82-11e6-832f-69c396480068.jpg)

**Comment by alsoscotland** [comment]
I will take a look at this too

**Comment by alsoscotland** [comment]
https://github.com/alsoscotland/react-super-select/pull/67
