### ISSUE TITLE
expand and close without selecting anything, the focus change over the list

### ISSUE THREAD

**Issue by amgohan** [alsoscotland/react-super-select#66]
try to expand and close the dropdown multiple time without selecting anything. You will see the focus change over the options.
this is some images from expand and close multiple times (the focus change over the list) : 
![react-select-bug1](https://cloud.githubusercontent.com/assets/3297683/15905727/e9fad99e-2d83-11e6-8114-a57ab54d092d.jpg)

![react-select-bug2](https://cloud.githubusercontent.com/assets/3297683/15905729/ed194368-2d83-11e6-81a3-e382b5ff10b3.jpg)

![react-select-bug3](https://cloud.githubusercontent.com/assets/3297683/15905735/f0aa99aa-2d83-11e6-9f6e-dc52ac1be169.jpg)

expected behaviour : no option focused until we select it manually

**Comment by alsoscotland** [comment]
This is related to the search input focus issue you brought up yesterday

**Comment by alsoscotland** [comment]
https://github.com/alsoscotland/react-super-select/pull/68

**Comment by alsoscotland** [comment]
https://github.com/alsoscotland/react-super-select/tree/v0.5.0
