### ISSUE TITLE
Enhancement : highlight searched input

### ISSUE THREAD

**Issue by amgohan** [alsoscotland/react-super-select#69]
when searching, we hope that searched input will be highlighted.

You can tell me if you want any help, I can code with you :)

**Comment by alsoscotland** [comment]
@amgohan Always happy to receive help.  Although I am not sure I want to add that to the default renderer.  I would prefer to make just pass the search term to the customRendering function.  A user supplied custom renderer could then handle the search highlight regular expression and markup

**Comment by alsoscotland** [comment]
https://github.com/alsoscotland/react-super-select/pull/71
adds the searchString as a 2nd parameter to the user-supplied custom template rendering function

**Comment by alsoscotland** [comment]
https://github.com/alsoscotland/react-super-select/tree/v0.5.0
