### ISSUE TITLE
Enhancement : option to position the search icon at the left

### ISSUE THREAD

**Issue by amgohan** [alsoscotland/react-super-select#73]
Hi  @alsoscotland I hope you are doing well.

I want to position the search magnifier to the right (to match our ux requirements), but I found that is hardcoded into the component code source.

Can you provide an option like "searchMagnifierIconToLeft" or tell me if there is another way to do it.

Thanks.

**Comment by alsoscotland** [comment]
@amgohan 
The styling rules for the control are all written with fairly minimal specificity.  You should be able to add a custom class to your wrapper with the customClass property http://alsoscotland.github.io/react-super-select/#customClass and then override any css you want to change by preceding rules with that class.

**Comment by amgohan** [comment]
:+1 thanks @alsoscotland I was able to fix it
