### ISSUE TITLE
ReactSuperSelect eats mouse scroll and keyboard events

### ISSUE THREAD

**Issue by reintroducing** [alsoscotland/react-super-select#77]
I found these two issues that I wanted to bring to your attention.

Firstly, when the dropdown is open and i'm scrolling through the page, as soon as my mouse scrolls into the dropdown the scrolling stops and I can no longer scroll.  This seems problematic because picture a dropdown at the bottom of a page.  As you scroll down all the way and open the dropdown, I assume you won't be able to access the dropdown contents that are out of view since you can't scroll down.  

Second, if I have the dropdown open (and mouse isn't even in it) and I try to run some kind of keyboard event (let's just say a user command+r to reload the page which is what I was trying to do at some point), the keyboard events dont get fired and react-super-select just seems to swallow them up.  For any keyboard events that don't have to do with accessibility of the open dropdown the events should just pass through so the user can use the keyboard as they'd like, even when the dropdown is open.

**Comment by alsoscotland** [comment]
@reintroducing 
I will look into this as well.

**Comment by alsoscotland** [comment]
I have a fix for he keyboard event issue.

As far as the scrolling is concerned.  I made the behavior that way intentionally.  otherwise if you scroll to the bottom of the results set, particularly in an infinitely paging result set, the page continues to scroll and it is not as usable.

**Comment by alsoscotland** [comment]
https://github.com/alsoscotland/react-super-select/pull/79

**Comment by reintroducing** [comment]
Thanks, perhaps an option to enable/disable this? That way if someone wants that functionality they can have it but if not then they can opt out?

**Comment by alsoscotland** [comment]
@reintroducing 
I was thinking something along the same lines.  It is a heavy handed choice so disabling via prop might make sense.  I will look into it.  Thank you for all the great feedback by the way

**Comment by reintroducing** [comment]
Absolutely, and thanks for all your work on this, really appreciate it.

**Comment by alsoscotland** [comment]
no worries

**Comment by alsoscotland** [comment]
added forceDefaultBrowserScrolling prop in https://github.com/alsoscotland/react-super-select/pull/79/commits/77ab3464c9d26716f721d5af1b8b71b5fc67d940

**Comment by alsoscotland** [comment]
@reintroducing 
https://github.com/alsoscotland/react-super-select/commit/1ef30d53ec02aacba1bfd5941eb2fbfa9cfc9c20
your idea of using componentDidMount for the onClose/onOpen callbacks ended up being better.  thanks!

**Comment by reintroducing** [comment]
Glad to hear it, thanks again!

**Comment by alsoscotland** [comment]
@reintroducing  if you use these new props please let me know if you run into any issues

**Comment by reintroducing** [comment]
To be 100% honest I ended up using react-select in the end.  If you want my reasoning I can certainly provide it but it boiled down to getting this done a few days ago :\
