### ISSUE TITLE
In IE9, Object.setPrototypeOf is not support

### ISSUE THREAD

**Issue by DuckMingBrother** [alsoscotland/react-super-select#89]
we tried babel-polyfill, the babel can't fix this issue too. can you fix this?

**Comment by alsoscotland** [comment]
@DuckMingBrother @kensomanpow
https://github.com/alsoscotland/react-super-select/tree/v0.5.10 may fix the issue.  Could you please give it a try?

**Comment by DuckMingBrother** [comment]
I tried 0.5.10, it's fix the problem.

but we meet other problem,

` ReactSuperSelect.prototype.componentWillUnmount = function componentWillUnmount() {
    document.removeEventListener('click', this._handleDocumentClick);
    document.removeEventListener('touchstart', this._handleDocumentClick);
  };`

in IE10, 11, above event listener not remove after componentWillUnmount,
and error is  **this._rssDOM.rssControl is undefined**, the code happened error
in the below code...can you fix this~~~thank you.

`ReactSuperSelect.prototype._handleDocumentClick = function _handleDocumentClick() {
    var event = Array.prototype.slice.call(arguments)[0],
        isTargetStillInDOM = document.body.contains(event.target);
    if (isTargetStillInDOM && !this._rssDOM.rssControl.contains(event.target)) { 
      if (this.state.isOpen) {
        this.setState({
          isOpen: false,
          focusedId: undefined
        });
      }
    }
  };`

**Comment by alsoscotland** [comment]
@DuckMingBrother I will take a look at this soon

**Comment by alsoscotland** [comment]
@DuckMingBrother 
This may correct the issue.  Please let me know
https://github.com/alsoscotland/react-super-select/tree/v0.5.11

**Comment by alsoscotland** [comment]
@DuckMingBrother Any news on whether this solved your problem?
