### ISSUE TITLE
Support for disabled options

### ISSUE THREAD

**Issue by tasiek** [alsoscotland/react-super-select#92]
In our application, we need a support for disabling options (visible but not active). 

It is used in HTML as disabled attribute on option element. We could have an optional "disabled" property in option object.

**Comment by alsoscotland** [comment]
@tasiek That is absolutely something this control should allow.  I will make a pull to add disabled-option support soon

**Comment by alsoscotland** [comment]
@tasiek 
I am back after being out sick a while.  I have put together a branch with disabled option support.  Next version will have it

**Comment by alsoscotland** [comment]
@tasiek 
released https://github.com/alsoscotland/react-super-select/tree/v0.5.12
It should allow for disabled options

**Comment by tasiek** [comment]
Works fine, thank you!

**Comment by alsoscotland** [comment]
👍
