### ISSUE TITLE
Clear selected options on data source change

### ISSUE THREAD

**Issue by VikLiegostaiev** [alsoscotland/react-super-select#93]
Hi, have one more problem :-)  if my dataSource is dynamically changed and i want to selected options become cleared with every changed what i should do? :) now, i just change state with the help of refs, but i recommend you to add some property as for example clearSelectedValuesOnDataSourceChange. Thanks :D

**Comment by alsoscotland** [comment]
@VikLiegostaiev That should be easy enough to add.  I am planning to create a new version in the next couple of days

**Comment by alsoscotland** [comment]
@VikLiegostaiev 
Added the new prop in https://github.com/alsoscotland/react-super-select/tree/v0.5.13
