### ISSUE TITLE
clicking an option highlights it, need an extra click to select

### ISSUE THREAD

**Issue by conor909** [alsoscotland/react-super-select#96]
When the dropdown is open, it seems when I click on a option it highlights it.  I then need an extra click to selected it.  Can I remove this extra click?

```
<Select
    initialValue={ selectedObject }
    clearable={ false }
    dataSource={ options }
    optionLabelKey="label"
    optionValueKey="value"
    onChange={ selected => onSelect(selected.value) }
    forceDefaultBrowserScrolling={true} />
```

**Comment by alsoscotland** [comment]
@conor909 I have not seen this behavior.  Can you tell me what browser or device you are seeing this in?

**Comment by conor909** [comment]
So I believe this was an error with my redux cycle, the value wasn't being passed down from props properly.

Thanks anyway
