### ISSUE TITLE
close select on selected option click 

### ISSUE THREAD

**Issue by VikLiegostaiev** [alsoscotland/react-super-select#97]
Hi again, can u please add a method that will close select when i click on already selected option :-)

**Comment by VikLiegostaiev** [comment]
Something like this:
```
if(alreadySelected) {
        if(!this.props.deselectOnSelectedOptionClick && this.props.closeOnSelectedOptionClick) {
                          
                    this._closeOnKeypress();
         }      
}

```

**Comment by alsoscotland** [comment]
@VikLiegostaiev Just an update:
looking into this.  Trying to make it behave like a native select control.  There is a little complication with multiselect/tag inputs.   Trying to work some bugs out for the moment

**Comment by alsoscotland** [comment]
https://github.com/alsoscotland/react-super-select/tree/v0.5.15
