### ISSUE TITLE
Append element

### ISSUE THREAD

**Issue by eduardobarbiero** [alsoscotland/react-super-select#99]
Hello People,
Is it possible to create a last element with a non-selectable option but an action?
Ex:
![capturar](https://cloud.githubusercontent.com/assets/9976687/24565334/3cb772e2-162b-11e7-8773-9f22dad37e97.PNG)

Thanks.

**Comment by alsoscotland** [comment]
@eduardobarbiero 
at the moment the only way to do something like this would be to leverage the custom option templating and do something hacky.  You would basically have to append a bogus option item to your data list, and switch the behavior of your template function's output for the link option

**Comment by eduardobarbiero** [comment]
Thanks @alsoscotland

So if it is not possible to implement in this way, i believe that preventing the click on the object is also not possible, correct?

**Comment by alsoscotland** [comment]
@eduardobarbiero 
I have decided not to implement this at this time because adding actionable elements which are not select options goes a bit against the select-control's normal paradigm
